Group rework
hyprwm/hyprland-wiki pull request #132
Opened 2023-02-21 23:45 UTC by Aqa-Ib

Changegroupactive backwards is not working at the moment though.

2023-02-21 23:55 UTC, vaxerski commented
Thanks. Completely forgot. Yeah, I know, it's in the issue tracker. Bug.

2023-02-21 23:55 UTC, vaxerski commented
tag me when ready to merge (looks ready to me?)

2023-02-22 00:01 UTC, Aqa-Ib commented
Alright, check if it is well written, or if you can explain it better than I did @vaxerski

2023-02-22 00:07 UTC, vaxerski commented
I would not make a new page. I would just write a quick inline description in the variables page.

2023-02-22 00:16 UTC, vaxerski commented
something like (probably in dispatchers is the best) `togglegroup | toggles a group. a group is a ... blah blah`

2023-02-22 00:43 UTC, Aqa-Ib commented
Check it when you can please.

2023-02-22 08:53 UTC, vaxerski requested changes

2023-02-22 08:53 UTC, vaxerski commented on pages/Configuring/Dispatchers.md
> +When creating the group, a group will be made from the current active window. Groups can be tiled, floating, and can be used in dwindle and master layouts.
layout note is redundant, they work regardless of the layout while this suggests they work _only_ on master and dwindel.

2023-02-22 08:53 UTC, vaxerski commented on pages/Configuring/Dispatchers.md
> +You can lock a group with the `lockgroups` bind dispatcher for an improved window management.
for ~~an~~ improved window management

2023-02-22 08:54 UTC, vaxerski commented
also you forgot to add the group dispatchers to the dispatcher list. You yote them from dwindle and didnt readd back

2023-02-22 13:19 UTC, Aqa-Ib commented
My bad. Fixed now, check it out please.

2023-02-22 15:05 UTC, vaxerski approved these changes
lgtm xd

2023-02-22 15:06 UTC, merged

2023-02-22 21:15 UTC, Aqa-Ib commented
Thanks and sorry for the trouble. Next time I will try to do it better than this.

2023-02-22 23:15 UTC, vaxerski commented
no worries