Fix some grammar/punctuation + rewrite stuff
hyprwm/hyprland-wiki pull request #605
Opened 2024-04-19 06:28 UTC by phonetic112

Some general grammar + punctuation cleanup, consolidation, rephrasing, etc.

2024-04-19 22:21 UTC, fufexan requested changes

2024-04-19 22:21 UTC, fufexan commented on pages/Configuring/Window-Rules.md
> +Opacity is a PRODUCT of all opacities by default. Setting `activeopacity` to 0.5
```suggestion
Opacity is a PRODUCT of all opacities by default. For example, setting `activeopacity` to 0.5 
```

2024-04-19 22:21 UTC, fufexan commented on pages/Getting Started/Installation.md
> +(if the pkg is available for Hyprland) or install/build it yourself.
```suggestion
(if there is a Hyprland package available) or install/build it yourself.
```

2024-04-19 22:21 UTC, fufexan commented on pages/Useful Utilities/xdg-desktop-portal-hyprland.md
> +If you see a crash, it's likely you are missing either `qt6-wayland` and/or
```suggestion
If you see a crash, it's likely you are missing either `qt6-wayland` or
```

2024-04-20 20:46 UTC, phonetic112 commented
should be good now

2024-04-21 14:35 UTC, fufexan approved these changes
LGTM! Thanks for the hard work!

2024-04-21 14:35 UTC, merged