add Minimize windows tip
hyprwm/hyprland-wiki pull request #626
Opened 2024-04-30 14:36 UTC by a-amr

issue #625

2024-04-30 15:36 UTC, vaxerski commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +you can alway create a special workspace and put whatever you want in it.
always

2024-04-30 15:36 UTC, vaxerski commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +However, this is a more intuitive way by using single keybind to minimize
a single keybind

2024-04-30 15:36 UTC, vaxerski commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +it or unminimize, every keybind can only minimize one window at a time.
, but every keybind...

2024-05-01 02:42 UTC, a-amr commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +it or unminimize, every keybind can only minimize one window at a time.
thank you 
fixed now

2024-05-01 02:44 UTC, a-amr commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +However, this is a more intuitive way by using single keybind to minimize
done

2024-05-01 02:44 UTC, a-amr commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +you can alway create a special workspace and put whatever you want in it.
done

2024-05-01 13:15 UTC, fufexan requested changes

2024-05-01 13:15 UTC, fufexan commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +##  Minimize Windows Using Special Sorkspaces
```suggestion
##  Minimize windows using special workspaces
```

2024-05-01 13:15 UTC, fufexan commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +you can always create a special workspace and put whatever you want in it.
Unnecessary.

2024-05-01 13:15 UTC, fufexan commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +it or unminimize, but every keybind can only minimize one window at a time.
```suggestion
This approach uses special workspaces to mimic the "minimize window" function, by using a single keybind to toggle the minimized state.
Note that one keybind can only handle one window.
```

2024-05-01 17:57 UTC, a-amr commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +you can always create a special workspace and put whatever you want in it.
maybe

2024-05-01 17:57 UTC, a-amr commented on pages/Configuring/Uncommon-tips-&-tricks.md
> +it or unminimize, but every keybind can only minimize one window at a time.
check it out

2024-05-01 17:58 UTC, a-amr commented
also don't forget to check the keybinding it self

2024-05-01 19:23 UTC, fufexan approved these changes

2024-05-01 19:24 UTC, merged