Installation: Add Chaotic AUR and `downgrade` mention
hyprwm/hyprland-wiki pull request #731
Opened 2024-08-01 08:37 UTC by Visual-Dawg

Just sharing what I find useful.

The Chaotic Aur is awesome and downgrade makes it quick and easy to, well, downgrade, especially with the Chaotic Aur.

2024-08-02 09:12 UTC, alba4k commented
> we recommend

chaotic-aur is a really nice thing to have, but I wouldn't officially recommend it as it isn't a great idea in principle. Of course it's not a complete anarchy, but I still think that sentence should be reworded sligthly

2024-08-02 19:14 UTC, Visual-Dawg commented
True, I changed it

2024-08-02 19:16 UTC, alba4k requested changes
pre-built not pre-build

also, the part after the comma doesn't really make sense grammatically


"and be able to perform easy downgrades", maybe?

2024-08-03 10:36 UTC, alba4k commented
It should probably also be made clear that this is all regarding Arch Linux, as NixOS is also officially supported

2024-08-03 13:19 UTC, Visual-Dawg commented
This is within the Arch Linux install card, so it should be clear enough

2024-08-03 13:31 UTC, alba4k commented
You're right, my bad ahah

2024-08-03 13:32 UTC, alba4k requested changes

2024-08-03 13:32 UTC, alba4k commented on pages/Getting Started/Installation.md
> +If you decide to use the `git` version, you can use the [Chaotic Aur](https://aur.chaotic.cx/) to get pre-built binaries.
maybe change this part to

> the `-git` version from the AUR

2024-08-06 12:01 UTC, fufexan approved these changes
LGTM

2024-08-06 12:01 UTC, merged

2025-10-24 13:56 UTC, alba4k commented
@vdawg-git I switched to repo packages a few weeks ago because I couldn't bother with chaotic aur anymore. It happens too often (I'd say once per month or so) that hyprland or some other component stops working because they often provide versions of libraries that don't match what they're building against.

An example of this is how every breaking `hyprutils` update often break hyprland etc, as they provide the new one but keep building against the old one for a while (and don't rebuild existing packages either), resulting in the provided executables looking for an older library that doesn't exist anymore (in this example, often `libhyprutils.so.(n-1)` when only `libhyprutils.so.n`) exists.

Maybe this should also be mentioned to avoid confusing people when (not if) it eventually happens?

2025-10-24 13:59 UTC, vdawg-git commented
@alba4k  Good idea, I also experienced this. 
Vax could also just bumb all package versions when there is an ABI break, but I suppose adding a warning or removing the chaotic AUR is better

2025-10-24 14:06 UTC, vdawg-git commented
@alba4k https://github.com/hyprwm/hyprland-wiki/pull/1264
Created a PR for that

2025-10-24 15:20 UTC, alba4k commented
I really don't think vaxry should be bothered to bump all versions because some packages don't know what they're doing