Add Debian to installation.md
hyprwm/hyprland-wiki pull request #733
Opened 2024-08-02 11:50 UTC by brrock

Simply add Debian as there is a package in the SID repos

2024-08-02 12:42 UTC, brrock commented on pages/Getting Started/Installation.md
> +{{% details title="Debain*" closed="true" %}}
Should be resolved

2024-08-02 20:18 UTC, fufexan requested changes

2024-08-02 20:18 UTC, fufexan commented on pages/Getting Started/Installation.md
> +Note: _Hyprland is not available for Bookworm as it packages are too old
```suggestion
{{< callout type=info >}}

Hyprland is not available for Bookworm as its packages are too old.

{{< /callout >}}
```

2024-08-03 06:39 UTC, brrock reviewed
Sorry for the typos I was on mobile

2024-08-03 17:23 UTC, brrock commented
@vaxerski

2024-08-04 09:54 UTC, fufexan approved these changes

2024-08-04 09:55 UTC, merged